### ISSUE TITLE
Hi.

### ISSUE THREAD

**Issue by vinodronold** [ProLoser/BakingPlate#19]
I m very new to GIT, tried forking BakingPlate, i m getting below error:

Administrator@HOME-NPR3MLGX9N /c/wamp/www/Plugin
$ cake plate
sh.exe": cake: command not found

**Comment by ProLoser** [comment]
From the wiki:

## BakingPlate assumes the following
- You know how to develop with CakePHP - you've [read the book](http://book.cakephp.org/) and been through the [blog tutorial](http://book.cakephp.org/view/1528/Blog) 
- **You have cake console installed ([win](http://tv.cakephp.org/video/gwoo/2010/12/24/setting_up_the_cakephp_console_on_windows) | [*nix](http://tv.cakephp.org/video/gwoo/2010/12/24/setting_up_the_cakephp_console_on_nix))**
- You're on reasonable terms with [GIT](http://help.github.com/), because we use [submodules](http://book.git-scm.com/5_submodules.html)

Follow the instructions for windows, let me know if you have any other problems.

**Comment by sams** [comment]
Using windows you will:

currently when BakingPlate adds submodules the path will contain `\\` when it should contain `/` - I will be pushing fix for this the add submodule needs to use `/` and not `DS` when adding submodule - its only a small thing

https://github.com/ProLoser/BakingPlate/blob/master/Console/Command/PlateShell.php#L320
